"""day2_models

Revision ID: 5c8b518a69b2
Revises: 
Create Date: 2026-03-04 23:03:40.528023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5c8b518a69b2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organisations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organisations_slug'), 'organisations', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('firebase_uid', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('last_login_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_firebase_uid'), 'users', ['firebase_uid'], unique=True)
    op.create_table('wcag_criteria',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('criterion_id', sa.String(length=20), nullable=False, comment="WCAG criterion identifier, e.g., '1.1.1'"),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('level', sa.String(length=3), nullable=False, comment='Conformance level: A, AA, or AAA'),
    sa.Column('wcag_version', sa.String(length=10), nullable=False, comment='WCAG version: 2.1 or 2.2'),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('understanding_url', sa.String(length=500), nullable=True, comment='Link to W3C Understanding document'),
    sa.CheckConstraint("level IN ('A', 'AA', 'AAA')", name='ck_wcag_level_valid'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wcag_criteria_criterion_id'), 'wcag_criteria', ['criterion_id'], unique=True)
    op.create_table('evaluation_projects',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('target_url', sa.String(length=2048), nullable=False),
    sa.Column('wcag_version', sa.String(length=10), nullable=False),
    sa.Column('conformance_level', sa.String(length=3), nullable=False),
    sa.Column('audit_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('scope_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Configuration for crawl scope: include/exclude patterns, max pages, etc.'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_evaluation_projects_organisation_id', 'evaluation_projects', ['organisation_id'], unique=False)
    op.create_table('user_organisation_roles',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.CheckConstraint("role IN ('owner', 'auditor', 'reviewer', 'viewer')", name='ck_user_org_role_valid'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'organisation_id', name='uq_user_organisation')
    )
    op.create_index(op.f('ix_user_organisation_roles_organisation_id'), 'user_organisation_roles', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_user_organisation_roles_user_id'), 'user_organisation_roles', ['user_id'], unique=False)
    op.create_table('pages',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('evaluation_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('page_type', sa.String(length=50), nullable=True, comment='Page type classification: homepage, contact, product, etc.'),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('in_sample', sa.Boolean(), nullable=False),
    sa.Column('sample_reason', sa.String(length=100), nullable=True, comment='Reason for including in sample: homepage, process-start, common-type, etc.'),
    sa.Column('crawl_status', sa.String(length=20), nullable=False),
    sa.Column('scan_status', sa.String(length=20), nullable=False),
    sa.Column('discovered_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('scanned_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('http_status', sa.SmallInteger(), nullable=True),
    sa.Column('screenshot_key', sa.String(length=500), nullable=True, comment='MinIO storage key for page screenshot'),
    sa.ForeignKeyConstraint(['evaluation_id'], ['evaluation_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('evaluation_id', 'url', name='uq_evaluation_page_url')
    )
    op.create_index('ix_pages_evaluation_id', 'pages', ['evaluation_id'], unique=False)
    op.create_index('ix_pages_evaluation_in_sample', 'pages', ['evaluation_id', 'in_sample'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('evaluation_id', sa.UUID(), nullable=False),
    sa.Column('generated_by', sa.UUID(), nullable=True),
    sa.Column('report_type', sa.String(length=30), nullable=False, comment='Report type: executive, full, earl, csv'),
    sa.Column('conformance_verdict', sa.String(length=30), nullable=True, comment='Verdict: CONFORMS, DOES_NOT_CONFORM, CANNOT_DETERMINE'),
    sa.Column('criteria_passed', sa.Integer(), nullable=True),
    sa.Column('criteria_failed', sa.Integer(), nullable=True),
    sa.Column('criteria_na', sa.Integer(), nullable=True, comment='Criteria marked as not applicable'),
    sa.Column('total_findings', sa.Integer(), nullable=True),
    sa.Column('storage_key', sa.String(length=500), nullable=True, comment='MinIO storage key for the report file'),
    sa.Column('generated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['evaluation_id'], ['evaluation_projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['generated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_evaluation_id'), 'reports', ['evaluation_id'], unique=False)
    op.create_table('findings',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('evaluation_id', sa.UUID(), nullable=False),
    sa.Column('page_id', sa.UUID(), nullable=False),
    sa.Column('criterion_id', sa.UUID(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False, comment='Finding source: axe-core, pa11y, or manual'),
    sa.Column('rule_id', sa.String(length=100), nullable=True, comment='Automated tool rule identifier'),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=True, comment='Severity: critical, serious, moderate, minor, info'),
    sa.Column('css_selector', sa.Text(), nullable=True),
    sa.Column('html_snippet', sa.Text(), nullable=True),
    sa.Column('impact', sa.Text(), nullable=True, comment='Description of the accessibility impact'),
    sa.Column('remediation', sa.Text(), nullable=True, comment='Suggested fix for the issue'),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewer_note', sa.Text(), nullable=True),
    sa.Column('screenshot_key', sa.String(length=500), nullable=True, comment='MinIO storage key for finding screenshot'),
    sa.Column('raw_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Raw JSON result from automated tool'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['criterion_id'], ['wcag_criteria.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['evaluation_id'], ['evaluation_projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_findings_criterion_id', 'findings', ['criterion_id'], unique=False)
    op.create_index('ix_findings_evaluation_id', 'findings', ['evaluation_id'], unique=False)
    op.create_index('ix_findings_evaluation_status', 'findings', ['evaluation_id', 'status'], unique=False)
    op.create_index('ix_findings_page_id', 'findings', ['page_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_findings_page_id', table_name='findings')
    op.drop_index('ix_findings_evaluation_status', table_name='findings')
    op.drop_index('ix_findings_evaluation_id', table_name='findings')
    op.drop_index('ix_findings_criterion_id', table_name='findings')
    op.drop_table('findings')
    op.drop_index(op.f('ix_reports_evaluation_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index('ix_pages_evaluation_in_sample', table_name='pages')
    op.drop_index('ix_pages_evaluation_id', table_name='pages')
    op.drop_table('pages')
    op.drop_index(op.f('ix_user_organisation_roles_user_id'), table_name='user_organisation_roles')
    op.drop_index(op.f('ix_user_organisation_roles_organisation_id'), table_name='user_organisation_roles')
    op.drop_table('user_organisation_roles')
    op.drop_index('ix_evaluation_projects_organisation_id', table_name='evaluation_projects')
    op.drop_table('evaluation_projects')
    op.drop_index(op.f('ix_wcag_criteria_criterion_id'), table_name='wcag_criteria')
    op.drop_table('wcag_criteria')
    op.drop_index(op.f('ix_users_firebase_uid'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_organisations_slug'), table_name='organisations')
    op.drop_table('organisations')
    # ### end Alembic commands ###
